load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "facecake_face_aar",
    calculators = ["//mediapipe/graphs/face_detection:mobile_calculators"],
)